version: '3.8'

services:
  # MySQL Database
  database:
    image: mysql:8.0
    container_name: university-database
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: university_db
      MYSQL_USER: university_user
      MYSQL_PASSWORD: password123
    ports:
      - "3307:3306"  # Use port 3307 instead
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    networks:
      - university-network

  # Spring Boot Backend
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: university-backend
    environment:
      SPRING_PROFILES_ACTIVE: production
      SPRING_DATASOURCE_URL: jdbc:mysql://database:3306/university_db
      SPRING_DATASOURCE_USERNAME: university_user
      SPRING_DATASOURCE_PASSWORD: password123
    ports:
      - "8080:8080"
    depends_on:
      database:
        condition: service_healthy
    networks:
      - university-network

  # React Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: university-frontend
    environment:
      REACT_APP_API_URL: http://backend:8080
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - university-network

# Define networks
networks:
  university-network:
    driver: bridge

# Define persistent volumes
volumes:
  mysql_data: